install.packages("plotly")
install.packages("rmarkdown")
#Dependencies of plotly/rmarkdown which may be necessary:
#install.packages("httr")
#install.packages("openssl")
#install.packages("stringi")
#install.packages("ggplot2")
install.packages("gplots")
install.packages("RColorBrewer")
install.packages("igraph")
install.packages("ROCR")
install.packages("igraph")
install.packages("randomForest")
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite("DOSE")
biocLite("limma")
